name: Build & Test CSPOT on a Single Eucalyptus Node

on: push

jobs:
  launch-instance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: one-script-to-rule-them-all # TODO: change to master before merging
          sparse-checkout: |
            .github/setup_euca.py
            .github/requirements.txt
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r .github/requirements.txt
      - name: Make runner
        run: .github/setup_euca.py codici2 --label single-euca-node --stop-on-error
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_ENDPOINT_URL: ${{ vars.AWS_ENDPOINT_URL }}
          AMI_IMAGE: ${{ vars.AMI_IMAGE }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          CICD_SSH_KEY: ${{ secrets.CICD_SSH_KEY }}
          EC2_CREATE_TIMEOUT: 450
          REPO_URL: "https://www.github.com/${{ github.repository }}"
          
  build-test:
    runs-on: [ self-hosted, Linux, x86_64, single-euca-node ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build & Install
        run: ./build-install.sh
