name: Create Org Runner

on: push

jobs:
  launch-instance:
    runs-on: ubuntu-latest
    outputs:
      json_response: ${{ steps.run-script.outputs.json_response }}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script file
        id: run-script
        run: .github/add_runner.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_RUNNER: ${{ secrets.CSPOT_CI-CD }}
