name: Run Stage 1

on: push

jobs:
  run-stage-1:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script file
        id: run-script
        run: ./.github/launch-runner.sh -n CSPOT_CI-CD
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Get curr ID, fill file
        env:
           CURR_ID: ${{ steps.run-script.outputs.CURR_ID }}
        run: |
          echo "curr id is $CURR_ID"
          echo "$CURR_ID" > ./.github/curr_id.txt # Create a dummy file
          git config --global user.name 'Oscar Benedek'
          git config --global user.email 'obenedek@users.noreply.github.com'
          git commit -m "Update ID"
          git push
      - name: Check contents of artifact
        run: cat ./.github/curr_id.txt
      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          name: curr-id
          path: ./.github/curr_id.txt
        
