name: Run Stage 1

on: push

jobs:
  launch-instance:
    runs-on: ubuntu-latest
    outputs:
      CURR_ID: ${{ steps.run-script.outputs.CURR_ID }}
      PUBLIC_IP: ${{ steps.run-script.outputs.PUBLIC_IP }}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script file
        id: run-script
        run: INPUT_STORE=$ADD_RUNNER .github/launch-runner.py -n CSPOT_CI-CD
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          ADD_RUNNER: ${{ secrets.ADD_RUNNER }}

  cspot-build-test:
    needs: launch-instance
    runs-on: [self-hosted, Linux, X64]
    continue-on-error: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: build & install
        run: ./build-install.sh
      # - name: test

  ssh-connect:
    needs: launch-instance
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: check IP
        run: |
          echo $PUBLIC_IP
          echo "CURR_ID: ${CURR_ID}"
          echo $SSH_KEY
        env:
          PUBLIC_IP: ${{ needs.launch-instance.outputs.PUBLIC_IP }}
          CURR_ID: ${{ needs.launch-instance.outputs.CURR_ID }}
          SSH_KEY: ${{ secrets.CICD_SSH_KEY }}
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: $PUBLIC_IP
          username: cloud-user
          key: $SSH_KEY
          port: 22
          script: echo "test"
        env:
          PUBLIC_IP: ${{ needs.launch-instance.outputs.PUBLIC_IP }}
          SSH_KEY: ${{ secrets.CICD_SSH_KEY }}

  terminate-runner:
    needs: [cspot-build-test, launch-instance]
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: run terminate script
        run: |
          echo "CURR_ID: ${CURR_ID}"
          .github/terminate.sh $CURR_ID
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
           CURR_ID: ${{ needs.launch-instance.outputs.CURR_ID }}
