name: Run Stage 1.

on: push

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Make executable
        run: chmod 750 stage1.sh
      - name: Run a script
        run: ./stage1.sh
