name: Run Stage 1

on: push

jobs:
  launch-instance:
    runs-on: ubuntu-latest
    outputs:
      CURR_ID: ${{ steps.run-script.outputs.CURR_ID }}
      PUBLIC_IP: ${{ steps.run-script.outputs.PUBLIC_IP }}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script file
        id: run-script
        run: .github/launch-runner.py -n CSPOT_CI-CD
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          ADD_RUNNER: ${{ secrets.ADD_RUNNER }}

  cspot-build-test:
    needs: launch-instance
    runs-on: [self-hosted, Linux, X64]
    continue-on-error: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: build & install
        run: ./build-install.sh
      # - name: test

  config-runner:
    needs: launch-instance
    runs-on: ubuntu-latest
    outputs:
      TOKEN: ${{ steps.run-config.outputs.token }}
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: run config script
        id: run-config
        run: |
          echo "TOKEN: ${TOKEN}"
          ./.github/config_runner.sh -t $ADD_RUNNER
        env:
          ADD_RUNNER: ${{ secrets.ADD_RUNNER }}

  ssh-connect1:
    needs: [launch-instance, config-runner]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set IP to Env Var
        run: |
          echo "PUBLIC_IP=${PUBLIC_IP}" >> $GITHUB_ENV
        env:
          PUBLIC_IP: ${{ needs.launch-instance.outputs.PUBLIC_IP }}
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.PUBLIC_IP }}
          username: cloud-user
          key: $SSH_KEY
          port: 22
          script: echo "setting up ssh connection"
        env:
          SSH_KEY: ${{ secrets.CICD_SSH_KEY }}
          TOKEN: ${{ needs.config-runner.outputs.TOKEN }}

  
  ssh-connect2:
    needs: [launch-instance, config-runner, ssh-connect1]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set IP to Env Var
        run: |
          echo "PUBLIC_IP=${PUBLIC_IP}" >> $GITHUB_ENV
        env:
          PUBLIC_IP: ${{ needs.launch-instance.outputs.PUBLIC_IP }}
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          envs: $TOKEN
          host: ${{ env.PUBLIC_IP }}
          username: cloud-user
          key: $SSH_KEY
          port: 22
          script: |
            ~/connect_runner.sh
        env:
          SSH_KEY: ${{ secrets.CICD_SSH_KEY }}
          TOKEN: ${{ needs.config-runner.outputs.TOKEN }}

  terminate-runner:
    needs: [cspot-build-test, launch-instance, ssh-connect2]
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: run terminate script
        run: |
          echo "CURR_ID: ${CURR_ID}"
          .github/terminate.sh $CURR_ID
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
           CURR_ID: ${{ needs.launch-instance.outputs.CURR_ID }}
