name: Run Stage 1.

on: push

jobs:
  run-stage-1:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
         ./stage1.sh
        shell: bash
