name: Test ssh

on: push

jobs:

  ssh-connect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 169.231.230.172
          username: cloud-user
          key: $SSH_KEY
          port: 22
          script: echo "test"
        env:
          SSH_KEY: ${{ secrets.CICD_SSH_KEY }}
